ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}

# Add kibana plugins setup here if it is needed
# Example: RUN kibana-plugin install <name|url>
