ARG ELASTIC_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}

# Add elasticsearch plugins setup here if it is needed
# Example: RUN elasticsearch-plugin install analysis-icu
