{
 "title": "BiodataAI Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Patients, encounters and Procedures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(biodatai_encounters_metrics) by (month)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(biodatai_procedures_metrics) by (month)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gap Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(biodatai_gap_average_metrics)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Appointments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(biodatai_appointments_metrics) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Procedures",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "biodatai_top_procedures_metrics",
     "legendFormat": "{{procedureName}}"
    }
   ]
  }
 ]
}